- name: update system packages 
  apt:  
    update_cache: yes  
    
- name: install iptables-persistent 
  command: apt install iptables-persistent   
  
- name: accepts all traffic on your loopback interface 
  command: iptables -A INPUT -i lo -j ACCEPT
  
 - name: accepts all traffic on your loopback interface
   command: iptables -A INPUT -o lo -j ACCEPT 
   
 - name: accepts established and related incoming connections 
   command: iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT 
   
 - name: accepts outgoing established connections  
   command: iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT  
   
 - name: allow traffic from internal interface to external interface 
   command: iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT 
   
 - name: drop invalid packets 
   command: iptables -A INPUT -m conntrack --ctstate INVALID -j DROP   
   
 - name: accept incoming connections from port 22 
   command: iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT  
   
 - name: allow otugoing established ssh connections 
   command: iptables -A OUTPUT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT 
   
 - name: allow rsync connection from specific ip address 
   command: "iptables -A INPUT -p tcp -s {{ backup_ipaddress }} --dport 873 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT" 
   
 - name: allow otugoing traffic rysnc connections
   command: iptables -A OUTPUT -p tcp --sport 873 -m conntrack --ctstate ESTABLSIHED -j ACCEPT 
   
 - name: allow incoming established postgresql connections  
   command: "iptables -A INPUT -p tcp -s {{ postgresconn_ipaddress }}  --dport 5432 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT"
   
 
 - name: allow outgoing established postgresql connections  
   command: iptables -A OUTPUT -p tcp --sport 5432 -m conntrack ESTABLISHED -j ACCEPT 
   
 - name: allow postgres to specific network interface  
   command: iptables -A INPUT -i eth1 -p tcp --dport 5432 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT 
   
 - name: allow outgoing traffic of established postgresql connection  
   command: iptables -A OUTPUT -o eth1 -p tcp --sport 5432 -m conntrack --ctstate ESTABLISHED -j ACCEPT
   
 - name: Then saves the current iptables rules 
   command: iptables -L > iptablesrules.txt
   
 
  
