- name: update system packages 
  apt:  
    update_cache: yes  
    
- name: install iptables-persistent 
  command: apt install iptables-persistent   
  

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes



- name: Allow new incoming SYN packets on TCP port 22 (SSH)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections    
      
   
      
 
-  name: allow incoming packets on TCP port 873 (rsync)
   ansible.builtin.iptables:
     chain: INPUT 
     protocol: tcp
     destination_port: 873
     ctstate: NEW
     jump: ACCEPT
     comment: accept rsync connections

 - name: allow outgoing packets on tcp port 873 (rsync)
   ansible.builtin.iptables:
     chain: OUTPUT
     protocol: tcp
     destination_port: 873
     ctstate: ESTABLISHED
     jump: ACCEPT
     comment: accept outgoing rsync connections

 
 - name: Allow incoming packets on TCP port 22 (SCP)
   ansible.builtin.iptables:
   chain: INPUT
   protocol: tcp
   destination_port: 22
   ctstate: NEW
   jump: ACCEPT

 - name: Allow outgoing packets on TCP port 22 (SCP)
   ansible.builtin.iptables:
     chain: OUTPUT
     protocol: tcp
     destination_port: 22
     ctstate: ESTABLISHED
     jump: ACCEPT
 
 
  - name: allow incoming packets on tcp port 5432 (postgresql)
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 5432
      ctstate: NEW
      jump: ACCEPT
      comment: accept incoming connections on port 5432


  - name: allow outgoing packets on tcp port 5432 (postgresql)
    ansible.builtin.iptables:
      chain: OUTPUT
      protocol: tcp
      destination_port: 5432
      ctstate: ESTABLISHED
      jump: ACCEPT
      comment: accept outgoing connections on port 5432

  
 
   
 
  
