
- name: upgrade the OS
  apt: 
    upgrade: dist 

- name: update cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600 


- sysctl:  
    name: kernel.shmmax
    value: 16777216 
    state: present 

- sysctl: 
    name: kernel.shmmall 
    value: 16777216
    state: present 

- sysctl: 
    name: vm.swappiness
    value: 1
    state: present 
    
- sysctl:  
    name: vm.nr_hugepages
    value: 88
    state: present
    
- sysctl: 
    name: vm.overcommit_memory
    value: 2 
    state: present 
    
- sysctl:  
    name: vm.overcommit_ratio
    value: 50%
    state: present
    
- sysctl:  
    name: vm.dirty_background_ratio  
    value: 10
    state: present 

- sysctl:   
    name: vm.dirty_ratio
    value: 20 
    state: present

