 
  
- name: install python version 3
  commmand: apt install -y python3-pip
  delegate_to: "{{ remote_host }}"
   
  
- name: install development packages for python 
  apt: name={{ item }} state=present 
  with_items: dev_packages    
      
- name: install hashlib module 
  command: pip3 install hashlib 
  
